name: map_location_picker
description: Google Map location picker for flutter Based on google_maps_flutter.
version: 1.2.0
homepage: https://github.com/rvndsngwn/map_location_picker

environment:
  sdk: ">=2.17.5 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
  google_maps_flutter: ^2.2.6
  form_builder_extra_fields: ^10.0.0
  flutter_typeahead: ^4.3.8
  google_maps_webapi: ^0.0.21
  google_maps_flutter_web: ^0.4.0+8
=======
  google_maps_flutter: ^2.2.3
  form_builder_extra_fields:
    git:
      url: https://github.com/rvndsngwn/form_builder_extra_fields.git
      publish_to: none
  flutter_typeahead: ^4.3.3
  google_maps_webservice: ^0.0.20-nullsafety.5
  google_maps_flutter_web: ^0.4.0+5
>>>>>>> db8251a (dependency updated)
  geolocator: ^9.0.2
  http: ^0.13.6
  logger: ^1.3.0
=======
  google_maps_flutter: ^2.2.1
=======
  google_maps_flutter: ^2.2.0
>>>>>>> a62ef21 (dependencies revert)
=======
  google_maps_flutter: 2.2.0
>>>>>>> 6a2a9d2 (Update pubspec.yaml)
  form_builder_extra_fields: ^8.3.0
  google_maps_webservice: ^0.0.20-nullsafety.5
  google_maps_flutter_web: ^0.4.0+2
  geolocator: 9.0.1
  #provider: ^6.0.3
  http: ^0.13.5
  logger: ^1.1.0
>>>>>>> f881d3c (package ui updated)

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1


flutter:

