name: map_location_picker
description: Google Map location picker for flutter Based on google_maps_flutter.
version: 1.2.7
homepage: https://github.com/mohesu/map_location_picker

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: ">=3.10.0"

flutter:
  plugin:
    platforms:
      android:
        default_package: google_maps_flutter_android
      ios:
        default_package: google_maps_flutter_ios
      web:
        default_package: google_maps_flutter_web

dependencies:
  flutter:
    sdk: flutter

  google_maps_flutter: ^2.5.0
  form_builder_extra_fields: ^10.1.0
  flutter_typeahead: ^4.8.0
  google_maps_webapi: ^0.0.22
  geolocator: ^10.1.0
  http: ^1.1.0
  logger: ^2.0.2+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^2.1.1
